#!/bin/bash

set -e
# create default cron-ms directory to put scripts
if [ ! -d "/etc/cron-ms/10" ]; then
  mkdir -p /etc/cron-ms/10
fi

if [ ! -d "/var/run/cron-ms" ]; then
  mkdir -p /var/run/cron-ms
fi

#DEBHELPER#
